all:
	gcc sdl2_animation.c -lSDL2 -lSDL2_gfx -lSDL2_ttf -lSDL2_image -lSDL2_mixer -L/usr/local/lib -I/usr/local/include/SDL2 -Wl,-rpath,/usr/local/lib -o sdl2_animation
	gcc sdl2_animation2.c -lSDL2 -lSDL2_gfx -lSDL2_ttf -lSDL2_image -lSDL2_mixer -L/usr/local/lib -I/usr/local/include/SDL2 -Wl,-rpath,/usr/local/lib -o sdl2_animation2
	gcc sdl2_animation3.c -lSDL2 -lSDL2_gfx -lSDL2_ttf -lSDL2_image -lSDL2_mixer -L/usr/local/lib -I/usr/local/include/SDL2 -Wl,-rpath,/usr/local/lib -o sdl2_animation3
